# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TravelRecord' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TravelRecord
  pod 'SnapKit', '~> 5.0.0'
  pod 'Then'
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'

  target 'TravelRecordTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TravelRecordUITests' do
    # Pods for testing
  end

end
